import fs from 'fs';
import path from 'path';
import axios from 'axios';

/**
 * Load configuration from .env.local file
 */
function loadConfig(configPath = '.env.local') {
  const config = {};
  
  if (!fs.existsSync(configPath)) {
    throw new Error(`Configuration file ${configPath} not found. Run 'ghcr config init' to create it.`);
  }
  
  const content = fs.readFileSync(configPath, 'utf8');
  const lines = content.split('\n');
  
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...valueParts] = trimmed.split('=');
      if (key && valueParts.length > 0) {
        config[key.trim()] = valueParts.join('=').trim();
      }
    }
  }
  
  return config;
}

/**
 * Save configuration to .env.local file
 */
function saveConfig(config, configPath = '.env.local') {
  const lines = [];
  
  // Add header comment
  lines.push('# GitHub Commit Workspace Runner Configuration');
  lines.push('# Generated by CLI');
  lines.push('');
  
  // Add configuration entries
  for (const [key, value] of Object.entries(config)) {
    lines.push(`${key}=${value}`);
  }
  
  fs.writeFileSync(configPath, lines.join('\n'));
}

/**
 * Validate GitHub token by making a test API call
 */
async function validateGitHubToken(token) {
  if (!token) {
    throw new Error('GitHub token is required');
  }
  
  try {
    const response = await axios.get('https://api.github.com/user', {
      headers: {
        'Authorization': `token ${token}`,
        'User-Agent': 'GitHub-Commit-Workspace-Runner-CLI'
      },
      timeout: 10000
    });
    
    if (response.status === 200) {
      return {
        valid: true,
        user: response.data.login,
        scopes: response.headers['x-oauth-scopes']?.split(', ') || []
      };
    } else {
      throw new Error(`GitHub API returned status ${response.status}`);
    }
  } catch (error) {
    if (error.response) {
      if (error.response.status === 401) {
        throw new Error('Invalid GitHub token');
      } else if (error.response.status === 403) {
        throw new Error('GitHub token has insufficient permissions');
      } else {
        throw new Error(`GitHub API error: ${error.response.status} ${error.response.statusText}`);
      }
    } else if (error.code === 'ENOTFOUND' || error.code === 'ECONNREFUSED') {
      throw new Error('Unable to connect to GitHub API. Check your internet connection.');
    } else {
      throw new Error(`Network error: ${error.message}`);
    }
  }
}

/**
 * Get default configuration values
 */
function getDefaultConfig() {
  return {
    SERVER_PORT: '4000',
    PUBLIC_SERVER_URL: 'http://localhost:4000',
    WORKSPACE_ROOT: './workspaces',
    MAX_FILE_SIZE: '1048576',
    RATE_LIMIT_MAX_REQUESTS: '60',
    SESSION_TIMEOUT_MINUTES: '60'
  };
}

/**
 * Merge user config with defaults
 */
function mergeWithDefaults(userConfig) {
  const defaults = getDefaultConfig();
  return { ...defaults, ...userConfig };
}

export {
  loadConfig,
  saveConfig,
  validateGitHubToken,
  getDefaultConfig,
  mergeWithDefaults
};
